{
    "DWF": {
        "references": [
            "https://www.suse.com/security/cve/CVE-2020-15207/"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "security-advisories@github.com",
            "ID": "CVE-2020-15207",
            "STATE": "PUBLIC",
            "TITLE": "Segfault and data corruption in tensorflow-lite"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "tensorflow",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "< 1.15.4"
                                            },
                                            {
                                                "version_value": ">= 2.0.0, < 2.0.3"
                                            },
                                            {
                                                "version_value": ">= 2.1.0, < 2.1.2"
                                            },
                                            {
                                                "version_value": ">= 2.2.0, < 2.2.1"
                                            },
                                            {
                                                "version_value": ">= 2.3.0, < 2.3.1"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "tensorflow"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "In tensorflow-lite before versions 1.15.4, 2.0.3, 2.1.2, 2.2.1 and 2.3.1, to mimic Python's indexing with negative values, TFLite uses `ResolveAxis` to convert negative values to positive indices. However, the only check that the converted index is now valid is only present in debug builds. If the `DCHECK` does not trigger, then code execution moves ahead with a negative index. This, in turn, results in accessing data out of bounds which results in segfaults and/or data corruption. The issue is patched in commit 2d88f470dea2671b430884260f3626b1fe99830a, and is released in TensorFlow versions 1.15.4, 2.0.3, 2.1.2, 2.2.1, or 2.3.1."
                }
            ]
        },
        "impact": {
            "cvss": {
                "attackComplexity": "HIGH",
                "attackVector": "NETWORK",
                "availabilityImpact": "HIGH",
                "baseScore": 8.7,
                "baseSeverity": "HIGH",
                "confidentialityImpact": "NONE",
                "integrityImpact": "HIGH",
                "privilegesRequired": "NONE",
                "scope": "CHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:H",
                "version": "3.1"
            }
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "{\"CWE-119\":\"Improper Restriction of Operations within the Bounds of a Memory Buffer\"}"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1",
                    "refsource": "MISC",
                    "url": "https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1"
                },
                {
                    "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-q4qf-3fc6-8x34",
                    "refsource": "CONFIRM",
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-q4qf-3fc6-8x34"
                },
                {
                    "name": "https://github.com/tensorflow/tensorflow/commit/2d88f470dea2671b430884260f3626b1fe99830a",
                    "refsource": "MISC",
                    "url": "https://github.com/tensorflow/tensorflow/commit/2d88f470dea2671b430884260f3626b1fe99830a"
                },
                {
                    "name": "openSUSE-SU-2020:1766",
                    "refsource": "SUSE",
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00065.html"
                }
            ]
        },
        "source": {
            "advisory": "GHSA-q4qf-3fc6-8x34",
            "discovery": "UNKNOWN"
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": [
                {
                    "children": [],
                    "cpe_match": [
                        {
                            "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:lite:*:*:*",
                            "cpe_name": [],
                            "versionEndExcluding": "1.15.4",
                            "vulnerable": true
                        },
                        {
                            "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:lite:*:*:*",
                            "cpe_name": [],
                            "versionEndExcluding": "2.0.3",
                            "versionStartIncluding": "2.0.0",
                            "vulnerable": true
                        },
                        {
                            "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:lite:*:*:*",
                            "cpe_name": [],
                            "versionEndExcluding": "2.1.2",
                            "versionStartIncluding": "2.1.0",
                            "vulnerable": true
                        },
                        {
                            "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:lite:*:*:*",
                            "cpe_name": [],
                            "versionEndExcluding": "2.2.1",
                            "versionStartIncluding": "2.2.0",
                            "vulnerable": true
                        },
                        {
                            "cpe23Uri": "cpe:2.3:a:google:tensorflow:*:*:*:*:lite:*:*:*",
                            "cpe_name": [],
                            "versionEndExcluding": "2.3.1",
                            "versionStartIncluding": "2.3.0",
                            "vulnerable": true
                        }
                    ],
                    "operator": "OR"
                }
            ]
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "security-advisories@github.com",
                "ID": "CVE-2020-15207"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "In tensorflow-lite before versions 1.15.4, 2.0.3, 2.1.2, 2.2.1 and 2.3.1, to mimic Python's indexing with negative values, TFLite uses `ResolveAxis` to convert negative values to positive indices. However, the only check that the converted index is now valid is only present in debug builds. If the `DCHECK` does not trigger, then code execution moves ahead with a negative index. This, in turn, results in accessing data out of bounds which results in segfaults and/or data corruption. The issue is patched in commit 2d88f470dea2671b430884260f3626b1fe99830a, and is released in TensorFlow versions 1.15.4, 2.0.3, 2.1.2, 2.2.1, or 2.3.1."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": [
                            {
                                "lang": "en",
                                "value": "CWE-119"
                            }
                        ]
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://github.com/tensorflow/tensorflow/commit/2d88f470dea2671b430884260f3626b1fe99830a",
                        "refsource": "MISC",
                        "tags": [
                            "Patch",
                            "Third Party Advisory"
                        ],
                        "url": "https://github.com/tensorflow/tensorflow/commit/2d88f470dea2671b430884260f3626b1fe99830a"
                    },
                    {
                        "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-q4qf-3fc6-8x34",
                        "refsource": "CONFIRM",
                        "tags": [
                            "Exploit",
                            "Third Party Advisory"
                        ],
                        "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-q4qf-3fc6-8x34"
                    },
                    {
                        "name": "https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1",
                        "refsource": "MISC",
                        "tags": [
                            "Third Party Advisory"
                        ],
                        "url": "https://github.com/tensorflow/tensorflow/releases/tag/v2.3.1"
                    },
                    {
                        "name": "openSUSE-SU-2020:1766",
                        "refsource": "SUSE",
                        "tags": [],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00065.html"
                    }
                ]
            }
        },
        "impact": {
            "baseMetricV2": {
                "acInsufInfo": false,
                "cvssV2": {
                    "accessComplexity": "MEDIUM",
                    "accessVector": "NETWORK",
                    "authentication": "NONE",
                    "availabilityImpact": "PARTIAL",
                    "baseScore": 6.8,
                    "confidentialityImpact": "PARTIAL",
                    "integrityImpact": "PARTIAL",
                    "vectorString": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
                    "version": "2.0"
                },
                "exploitabilityScore": 8.6,
                "impactScore": 6.4,
                "obtainAllPrivilege": false,
                "obtainOtherPrivilege": false,
                "obtainUserPrivilege": false,
                "severity": "MEDIUM",
                "userInteractionRequired": false
            },
            "baseMetricV3": {
                "cvssV3": {
                    "attackComplexity": "HIGH",
                    "attackVector": "NETWORK",
                    "availabilityImpact": "HIGH",
                    "baseScore": 9.0,
                    "baseSeverity": "CRITICAL",
                    "confidentialityImpact": "HIGH",
                    "integrityImpact": "HIGH",
                    "privilegesRequired": "NONE",
                    "scope": "CHANGED",
                    "userInteraction": "NONE",
                    "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:H",
                    "version": "3.1"
                },
                "exploitabilityScore": 2.2,
                "impactScore": 6.0
            }
        },
        "lastModifiedDate": "2021-08-17T13:21Z",
        "publishedDate": "2020-09-25T19:15Z"
    }
}